In [30]:
import numpy as np
import pandas as pd

import statsmodels.api as sm
import statsmodels.formula.api as smf

In [31]:
df = pd.read_excel('/Users/phu/Documents/K_31/EDA_K31/data/data-vn.xlsx', sheet_name='Data')
df

       Khu vực  Số người  Thu nhập  Chi tiêu  Chi ăn uống
0    Thành thị         1     186.0      71.2         43.7
1    Thành thị         1      18.0      19.2         14.7
2    Thành thị         1      61.5      15.0         11.9
3    Thành thị         1      48.1      57.9         46.9
4    Thành thị         1      30.0      20.6         13.7
..         ...       ...       ...       ...          ...
415  Nông thôn         8     153.4     104.1         84.8
416  Nông thôn         8     348.5     167.3        100.2
417  Nông thôn         8     220.6     106.9         80.6
418  Nông thôn         9     232.1     173.0        126.6
419  Nông thôn         9     137.6     167.1        155.2

[420 rows x 5 columns]

In [32]:
df['khu_vuc'] = df['Khu vực'].map(lambda x: 1 if x == 'Thành thị' else 0)
df

       Khu vực  Số người  Thu nhập  Chi tiêu  Chi ăn uống  khu_vuc
0    Thành thị         1     186.0      71.2         43.7        1
1    Thành thị         1      18.0      19.2         14.7        1
2    Thành thị         1      61.5      15.0         11.9        1
3    Thành thị         1      48.1      57.9         46.9        1
4    Thành thị         1      30.0      20.6         13.7        1
..         ...       ...       ...       ...          ...      ...
415  Nông thôn         8     153.4     104.1         84.8        0
416  Nông thôn         8     348.5     167.3        100.2        0
417  Nông thôn         8     220.6     106.9         80.6        0
418  Nông thôn         9     232.1     173.0        126.6        0
419  Nông thôn         9     137.6     167.1        155.2        0

[420 rows x 6 columns]

In [33]:
results = smf.ols("Q('Chi tiêu') ~ Q('Thu nhập') + Q('Số người') + khu_vuc", data=df).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          Q('Chi tiêu')   R-squared:                       0.730
Model:                            OLS   Adj. R-squared:                  0.728
Method:                 Least Squares   F-statistic:                     374.0
Date:                Sat, 02 Jul 2022   Prob (F-statistic):          1.05e-117
Time:                        15:21:03   Log-Likelihood:                -2156.8
No. Observations:                 420   AIC:                             4322.
Df Residuals:                     416   BIC:                             4338.
Df Model:                           3
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         2.3987      5.882      0.408      0.684      -9.163      13.960
Q('Thu nhập')     0.5145      0.023     22.532      0.000       0.470       0.559
Q('Số người')     3.6981      1.488      2.485      0.013       0.773       6.624
khu_vuc          32.0483      4.669      6.864      0.000      22.871      41.226
==============================================================================
Omnibus:                      112.288   Durbin-Watson:                   1.795
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              554.959
Skew:                           1.056   Prob(JB):                    3.11e-121
Kurtosis:                       8.220   Cond. No.                         565.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [34]:
results = smf.ols("Q('Chi tiêu') ~ np.log(Q('Thu nhập')) + Q('Số người') + khu_vuc", data=df).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          Q('Chi tiêu')   R-squared:                       0.588
Model:                            OLS   Adj. R-squared:                  0.585
Method:                 Least Squares   F-statistic:                     197.7
Date:                Sat, 02 Jul 2022   Prob (F-statistic):           1.13e-79
Time:                        15:21:03   Log-Likelihood:                -2245.3
No. Observations:                 420   AIC:                             4499.
Df Residuals:                     416   BIC:                             4515.
Df Model:                           3
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept              -192.9105     15.377    -12.545      0.000    -223.137    -162.684
np.log(Q('Thu nhập'))    58.2411      4.226     13.783      0.000      49.935      66.547
Q('Số người')             2.1247      2.038      1.042      0.298      -1.882       6.131
khu_vuc                  38.7586      5.988      6.472      0.000      26.987      50.530
==============================================================================
Omnibus:                      192.724   Durbin-Watson:                   1.813
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1218.989
Skew:                           1.870   Prob(JB):                    1.99e-265
Kurtosis:                      10.461   Cond. No.                         40.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [35]:
results = smf.ols("np.log(Q('Chi tiêu')) ~ Q('Thu nhập') + Q('Số người') + khu_vuc", data=df).fit()
print(results.summary())

                              OLS Regression Results
=================================================================================
Dep. Variable:     np.log(Q('Chi tiêu'))   R-squared:                       0.674
Model:                               OLS   Adj. R-squared:                  0.671
Method:                    Least Squares   F-statistic:                     286.1
Date:                   Sat, 02 Jul 2022   Prob (F-statistic):          9.98e-101
Time:                           15:21:03   Log-Likelihood:                -247.94
No. Observations:                    420   AIC:                             503.9
Df Residuals:                        416   BIC:                             520.0
Df Model:                              3
Covariance Type:               nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         3.1141      0.062     49.843      0.000       2.991       3.237
Q('Thu nhập')     0.0036      0.000     14.724      0.000       0.003       0.004
Q('Số người')     0.1454      0.016      9.200      0.000       0.114       0.177
khu_vuc           0.4358      0.050      8.787      0.000       0.338       0.533
==============================================================================
Omnibus:                       43.664   Durbin-Watson:                   1.289
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               68.721
Skew:                          -0.680   Prob(JB):                     1.19e-15
Kurtosis:                       4.440   Cond. No.                         565.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [36]:
results = smf.ols("np.log(Q('Chi tiêu')) ~ np.log(Q('Thu nhập')) + Q('Số người') + khu_vuc", data=df).fit()
print(results.summary())

                              OLS Regression Results
=================================================================================
Dep. Variable:     np.log(Q('Chi tiêu'))   R-squared:                       0.777
Model:                               OLS   Adj. R-squared:                  0.776
Method:                    Least Squares   F-statistic:                     484.0
Date:                   Sat, 02 Jul 2022   Prob (F-statistic):          3.03e-135
Time:                           15:21:03   Log-Likelihood:                -167.63
No. Observations:                    420   AIC:                             343.3
Df Residuals:                        416   BIC:                             359.4
Df Model:                              3
Covariance Type:               nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 0.8760      0.109      8.017      0.000       0.661       1.091
np.log(Q('Thu nhập'))     0.6792      0.030     22.619      0.000       0.620       0.738
Q('Số người')             0.0559      0.014      3.857      0.000       0.027       0.084
khu_vuc                   0.2699      0.043      6.342      0.000       0.186       0.354
==============================================================================
Omnibus:                       11.513   Durbin-Watson:                   1.715
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               16.367
Skew:                          -0.224   Prob(JB):                     0.000279
Kurtosis:                       3.857   Cond. No.                         40.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [37]:
df['X'] = df['Thu nhập'] + df['Số người']
df

       Khu vực  Số người  Thu nhập  Chi tiêu  Chi ăn uống  khu_vuc      X
0    Thành thị         1     186.0      71.2         43.7        1  187.0
1    Thành thị         1      18.0      19.2         14.7        1   19.0
2    Thành thị         1      61.5      15.0         11.9        1   62.5
3    Thành thị         1      48.1      57.9         46.9        1   49.1
4    Thành thị         1      30.0      20.6         13.7        1   31.0
..         ...       ...       ...       ...          ...      ...    ...
415  Nông thôn         8     153.4     104.1         84.8        0  161.4
416  Nông thôn         8     348.5     167.3        100.2        0  356.5
417  Nông thôn         8     220.6     106.9         80.6        0  228.6
418  Nông thôn         9     232.1     173.0        126.6        0  241.1
419  Nông thôn         9     137.6     167.1        155.2        0  146.6

[420 rows x 7 columns]

In [38]:
results = smf.ols("Q('Chi tiêu') ~ Q('Thu nhập') + Q('Số người') + khu_vuc + X", data=df).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          Q('Chi tiêu')   R-squared:                       0.730
Model:                            OLS   Adj. R-squared:                  0.728
Method:                 Least Squares   F-statistic:                     374.0
Date:                Sat, 02 Jul 2022   Prob (F-statistic):          1.05e-117
Time:                        15:21:04   Log-Likelihood:                -2156.8
No. Observations:                 420   AIC:                             4322.
Df Residuals:                     416   BIC:                             4338.
Df Model:                           3
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         2.3987      5.882      0.408      0.684      -9.163      13.960
Q('Thu nhập')    -0.8897      0.503     -1.768      0.078      -1.879       0.099
Q('Số người')     2.2939      0.996      2.304      0.022       0.337       4.251
khu_vuc          32.0483      4.669      6.864      0.000      22.871      41.226
X                 1.4042      0.493      2.850      0.005       0.436       2.373
==============================================================================
Omnibus:                      112.288   Durbin-Watson:                   1.795
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              554.959
Skew:                           1.056   Prob(JB):                    3.11e-121
Kurtosis:                       8.220   Cond. No.                     6.01e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 7.67e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [39]:
# df = pd.read_excel('/Users/phu/Documents/K_31/EDA_K31/data/data-vn.xlsx', sheet_name='Data')
# df

In [40]:
df.corr(method='pearson')

             Số người  Thu nhập  Chi tiêu  Chi ăn uống   khu_vuc         X
Số người     1.000000  0.395153  0.351237     0.445791 -0.017638  0.406658
Thu nhập     0.395153  1.000000  0.835696     0.770704  0.444672  0.999921
Chi tiêu     0.351237  0.835696  1.000000     0.949366  0.519178  0.835917
Chi ăn uống  0.445791  0.770704  0.949366     1.000000  0.491807  0.772574
khu_vuc     -0.017638  0.444672  0.519178     0.491807  1.000000  0.441994
X            0.406658  0.999921  0.835917     0.772574  0.441994  1.000000

In [41]:
df.corr(method='spearman')

             Số người  Thu nhập  Chi tiêu  Chi ăn uống   khu_vuc         X
Số người     1.000000  0.487752  0.434057     0.483542 -0.015997  0.500964
Thu nhập     0.487752  1.000000  0.836681     0.799448  0.479035  0.999786
Chi tiêu     0.434057  0.836681  1.000000     0.981943  0.540323  0.837225
Chi ăn uống  0.483542  0.799448  0.981943     1.000000  0.496620  0.801011
khu_vuc     -0.015997  0.479035  0.540323     0.496620  1.000000  0.474817
X            0.500964  0.999786  0.837225     0.801011  0.474817  1.000000

In [43]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

# VIF dfframe
new_df = df.pop('Khu vực')

vif_df = pd.DataFrame()
vif_df["feature"] = df.columns

# calculating VIF for each feature
vif_df["VIF"] = [variance_inflation_factor(df.values, i)
						for i in range(len(df.columns))]

print(vif_df)

       feature        VIF
0     Số người        inf
1     Thu nhập        inf
2     Chi tiêu  42.726881
3  Chi ăn uống  38.477652
4      khu_vuc   2.411061
5            X        inf

/Users/phu/opt/anaconda3/envs/EdaK31/lib/python3.7/site-packages/statsmodels/stats/outliers_influence.py:195: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)